package nodes_test

import (
	"context"
	"testing"

	"axiom-official/axiom-durable-test/axiom"
)

// testContext is a testing.T-backed axiom.Context shared by every *_test.go in
// this package. Each test file's CLI scaffold defined its own copy; that
// produced duplicate declarations once the package had 2+ nodes, so we keep a
// single canonical definition here.
type testContext struct {
	t          *testing.T
	secretsMap map[string]string
	reflection axiom.Reflection
}

func newTestContext(t *testing.T) *testContext {
	return &testContext{
		t:          t,
		secretsMap: map[string]string{},
		reflection: testReflection{}, // empty by default; nodes can override
	}
}

type testLogger struct{ t *testing.T }

func (l *testLogger) Debug(msg string, args ...any) { l.t.Logf("DEBUG  %s %v", msg, args) }
func (l *testLogger) Info(msg string, args ...any)  { l.t.Logf("INFO   %s %v", msg, args) }
func (l *testLogger) Warn(msg string, args ...any)  { l.t.Logf("WARN   %s %v", msg, args) }
func (l *testLogger) Error(msg string, args ...any) { l.t.Logf("ERROR  %s %v", msg, args) }

type testSecrets struct{ m map[string]string }

func (s testSecrets) Get(name string) (string, bool) { v, ok := s.m[name]; return v, ok }

func (c *testContext) Log() axiom.Logger            { return &testLogger{c.t} }
func (c *testContext) Secrets() axiom.Secrets       { return testSecrets{c.secretsMap} }
func (c *testContext) ExecutionID() string          { return "test-execution-id" }
func (c *testContext) FlowID() string               { return "test-flow-id" }
func (c *testContext) TenantID() string             { return "test-tenant-id" }
func (c *testContext) Reflection() axiom.Reflection { return c.reflection }

// ADR-051 (2026-05-26): ax.Mutation().Flow().AddNode / AddEdge stub for
// node-under-test compilation. Tests don't exercise the mutation path
// — calling AddNode/AddEdge through this stub is a no-op. The fixture
// is regenerated by `axiom push` from the current CLI template, which
// since SAF-001 requires axiom.Context.Mutation() to compile.
func (c *testContext) Mutation() axiom.Mutation { return testMutation{} }

type testMutation struct{}

func (testMutation) Flow() axiom.FlowMutation { return testFlowMutation{} }

type testFlowMutation struct{}

func (testFlowMutation) AddNode(_, _ string, _ *axiom.CanvasPosition) uint32 { return 0 }
func (testFlowMutation) AddEdge(_, _ uint32, _ *axiom.EdgeCondition)         {}

// ADR-128/129 (2026-07-11): axiom.Context gained Agent() (ax.Agent().Memory().*)
// for the agentic-memory surface. `axiom push` regenerates the fixture's axiom/
// package from the current CLI template, so the Context interface assertion below
// now requires Agent() to compile. These fixtures don't exercise the memory path,
// so inject an empty agent/memory — the same no-op-stub pattern as Mutation()
// and Reflection() above.
func (c *testContext) Agent() axiom.Agent { return testAgent{} }

type testAgent struct{}

func (testAgent) Memory() axiom.AgentMemory { return testAgentMemory{} }

type testAgentMemory struct{}

func (testAgentMemory) Session(string) axiom.SessionMemory { return testSessionMemory{} }
func (testAgentMemory) Search(context.Context, string, int) ([]axiom.MemoryEntry, error) {
	return nil, nil
}
func (testAgentMemory) Write(context.Context, string, float32) (string, error) { return "", nil }

type testSessionMemory struct{}

func (testSessionMemory) Search(context.Context, string, int) ([]axiom.MemoryEntry, error) {
	return nil, nil
}
func (testSessionMemory) Write(context.Context, string, float32) (string, error) { return "", nil }
func (testSessionMemory) History() axiom.SessionHistory                          { return testSessionHistory{} }
func (testSessionMemory) End(context.Context) error                              { return nil }

type testSessionHistory struct{}

func (testSessionHistory) Last(context.Context, int) ([]axiom.ConversationTurn, error) {
	return nil, nil
}
func (testSessionHistory) Append(context.Context, string, string) error { return nil }

var _ axiom.Context = (*testContext)(nil)

// ADR-050 (2026-05-26): testReflection lets a test inject a deterministic
// FlowReflection so node-under-test logic can be exercised without running
// the worker. The default newTestContext returns an empty FlowReflection
// (no nodes / no edges / zero position) so existing nodes (Identity, Echo,
// etc.) don't need to set anything. ReflectionProbe is the first node
// where the reflection contents matter, so its test injects a populated
// fixture.

type testReflection struct {
	flow axiom.FlowReflection
}

func (r testReflection) Flow() axiom.FlowReflection {
	if r.flow == nil {
		return emptyFlowReflection{}
	}
	return r.flow
}

type emptyFlowReflection struct{}

func (emptyFlowReflection) Nodes() []axiom.ReflectionNode     { return nil }
func (emptyFlowReflection) Edges() []axiom.ReflectionEdge     { return nil }
func (emptyFlowReflection) LoopEdges() []axiom.ReflectionEdge { return nil }
func (emptyFlowReflection) Position() axiom.FlowPosition      { return axiom.FlowPosition{} }
func (emptyFlowReflection) GraphID() string                   { return "" }

// fixtureFlowReflection is a fully-populated FlowReflection used by
// reflection_probe_test.go. Mirrors the structure the worker would
// construct for a 2-node graph: Identity (instance 0) → ReflectionProbe
// (instance 1).
type fixtureFlowReflection struct {
	nodes     []axiom.ReflectionNode
	edges     []axiom.ReflectionEdge
	loopEdges []axiom.ReflectionEdge
	position  axiom.FlowPosition
	graphID   string
}

func (f fixtureFlowReflection) Nodes() []axiom.ReflectionNode     { return f.nodes }
func (f fixtureFlowReflection) Edges() []axiom.ReflectionEdge     { return f.edges }
func (f fixtureFlowReflection) LoopEdges() []axiom.ReflectionEdge { return f.loopEdges }
func (f fixtureFlowReflection) Position() axiom.FlowPosition      { return f.position }
func (f fixtureFlowReflection) GraphID() string                   { return f.graphID }
