// Code generated by Axiom CLI; DO NOT EDIT.

// Package axiom provides the Context interface and all platform capabilities
// injected into every node function.
//
// All capabilities are accessed through the single ax parameter:
//
//	ax.Log().Info("order processed", "order_id", "abc123", "total", 99.99)
//	apiKey, ok := ax.Secrets().Get("ANTHROPIC_API_KEY")
//	turns, err := ax.Agent().Memory().Session("s1").History().Last(ctx, 20)
//
// Adding new platform capabilities requires no change to node function
// signatures — they are accessed via the Context interface.
package axiom

import "context"

// Logger is a structured logger pre-configured for a single node invocation.
// Concurrent invocations each receive their own Logger instance — never share
// a Logger across calls. The platform injects it via Context; node authors
// never construct one directly.
type Logger interface {
	Debug(msg string, args ...any)
	Info(msg string, args ...any)
	Warn(msg string, args ...any)
	Error(msg string, args ...any)
}

// Secrets provides read-only access to the tenant secrets resolved by the
// platform at invocation time. Values are plaintext strings; the platform
// handles encryption and decryption. Node authors never construct a Secrets
// instance directly — the platform injects it via Context on every invocation.
type Secrets interface {
	// Get returns the value for the named secret and true when present.
	// Returns ("", false) when the secret was not resolved for this invocation.
	Get(name string) (string, bool)
}

// ADR-002 (2026-04-19): memory is namespaced under Agent to separate
// agent-specific capabilities from general-purpose platform utilities.
// Future agent capabilities (Pause, Reflect, Interrupt) will also live here.

// ConversationTurn is a single message in an episodic session history.
type ConversationTurn struct {
	ID         string
	SessionID  string
	Role       string // "user" | "assistant" | "tool" | "system"
	Content    string
	ToolName   string
	ToolCallID string
	CreatedAt  int64 // unix millis
}

// MemoryEntry is a semantic or episodic memory retrieved from the memory layer.
type MemoryEntry struct {
	ID         string
	ScopeLevel string
	MemoryType string
	Content    string
	Importance float32
	Confidence float32
	Score      float32 // relevance score, populated on retrieval
	CreatedAt  int64
}

// SessionHistory provides access to the episodic turn-by-turn history for a
// specific session. Obtain via ax.Agent().Memory().Session(id).History().
type SessionHistory interface {
	// Last returns the most recent n turns, oldest-first (for LLM context injection).
	Last(ctx context.Context, n int) ([]ConversationTurn, error)
	// Append adds a new turn to this session's history.
	// role is "user" | "assistant" | "tool" | "system"
	Append(ctx context.Context, role, content string) error
}

// SessionMemory provides semantic memory and history access scoped to a single
// session. Obtain via ax.Agent().Memory().Session(id).
type SessionMemory interface {
	// Search finds the most relevant memories for this session and its flow.
	Search(ctx context.Context, query string, limit int) ([]MemoryEntry, error)
	// Write stores a semantic memory scoped to this session.
	Write(ctx context.Context, content string, importance float32) (string, error)
	// History returns the episodic history accessor for this session.
	History() SessionHistory
	// End formally closes the session and triggers consolidation.
	End(ctx context.Context) error
}

// AgentMemory provides access to the full memory hierarchy for this flow.
// Obtain via ax.Agent().Memory().
type AgentMemory interface {
	// Session returns memory scoped to a specific session ID.
	// The session ID comes from the typed input payload — never inferred.
	Session(sessionID string) SessionMemory
	// Search queries semantic memory across all sessions for this flow.
	Search(ctx context.Context, query string, limit int) ([]MemoryEntry, error)
	// Write stores a durable memory at the flow scope (persists across sessions).
	Write(ctx context.Context, content string, importance float32) (string, error)
}

// Agent holds all agent-specific platform capabilities.
// Obtain via ax.Agent().
type Agent interface {
	Memory() AgentMemory
}

// Context is the single platform capability injection point for every node
// handler function. It is passed as the second parameter (ax) to every handler:
//
//	func MyNode(ctx context.Context, ax axiom.Context, input *gen.MyRequest) (*gen.MyResponse, error) {
//	    ax.Log().Info("handling", "id", input.GetId())
//	    key, ok := ax.Secrets().Get("MY_SECRET")
//	    turns, err := ax.Agent().Memory().Session(input.GetSessionId()).History().Last(ctx, 20)
//	    ...
//	}
//
// Adding new platform capabilities requires no change to existing node
// function signatures — all capabilities are accessed via methods on Context.
type Context interface {
	// Log returns the structured logger for this invocation. Use instead of fmt.Println.
	Log() Logger

	// Secrets returns the tenant secrets resolver for this invocation.
	// Use for API keys and connection strings.
	Secrets() Secrets

	// Agent returns the agent capability bundle for this invocation.
	// Use ax.Agent().Memory() to access the memory layer.
	Agent() Agent

	// ExecutionID returns the UUID of the current execution.
	ExecutionID() string

	// FlowID returns the stable ID of the graph artifact (constant across executions).
	FlowID() string

	// TenantID returns the UUID of the tenant that owns this invocation.
	TenantID() string
}
